### ISSUE TITLE
Security section in readme

### ISSUE THREAD

**Issue by guidobouman** [kriskuiper/real-time-web-1920#14]
You've focused quite a bit on security, awesome. It would be good to also write about this in your readme. That way we can understand your intended process, and test your app / knowledge against this process.

**Comment by kriskuiper** [comment]
#13 Has to be finished first

**Comment by kriskuiper** [comment]
Thanks for your feedback! I will definitely add some documentation about security to my readme. 📚

**Comment by kriskuiper** [comment]
Added, maybe have to rewrite it a bit but we'll see. Thats out of the scope of this ticket.
